/* eslint-disable react/react-in-jsx-scope */
import Head from 'next/head';
import Banner from '../components/Banner';
import Row from '../components/Row';
import {request} from "../utils/request"
import { wrapper } from '../redux/store';
import { useSelector } from 'react-redux';
import { getNetflixOriginalsFilm, getTrendingFilm, getTopRatedFilm, getHistoryFilm, getScienceFictionFilm, getActionFilm, getDocumentariesFilm, getAnimationFilm, getAdventureFilm, getRomanceFilm, getComedyFilm, getHorrorFilm, getFantasyFilm, getCrimeFilm, getDramaFilm, getFamilyFilm } from '../redux/filmReducer';

export default function Home() {
  const netflixOriginals = useSelector((state) => state.films.netflixOriginals)
  const trending = useSelector((state) => state.films.trending)
  const topRated = useSelector((state) => state.films.topRated)
  const history = useSelector((state) => state.films.history)
  const scienceFiction = useSelector((state) => state.films.scienceFiction)
  const action = useSelector((state) => state.films.action)
  const documentaries = useSelector((state) => state.films.documentaries)
  const animation = useSelector((state) => state.films.animation)
  const adventure = useSelector((state) => state.films.adventure)
  const romance = useSelector((state) => state.films.romance)
  const comedy = useSelector((state) => state.films.comedy)
  const horror = useSelector((state) => state.films.horror)
  const crime = useSelector((state) => state.films.crime)
  const drama = useSelector((state) => state.films.drama)
  const fantasy = useSelector((state) => state.films.fantasy)
  const family = useSelector((state) => state.films.family)


  return (
    <div>
      <Head>
        <title>Netflux</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner />
        <section className="flex flex-col gap-y-8 pl-12">
          <Row CategoryTitle={"Netflix Originals"} filmsCategory={netflixOriginals}/>
          <Row CategoryTitle={"Top Rated"} filmsCategory={topRated}/>
          <Row CategoryTitle={"Trending"} filmsCategory={trending}/>
          <Row CategoryTitle={"History"} filmsCategory={history}/>
          <Row CategoryTitle={"ScienceFiction"} filmsCategory={scienceFiction}/>
          <Row CategoryTitle={"Action"} filmsCategory={action}/>
          <Row CategoryTitle={"Documentaries"} filmsCategory={documentaries}/>
          <Row CategoryTitle={"Animation"} filmsCategory={animation}/>
          <Row CategoryTitle={"Adventure"} filmsCategory={adventure}/>
          <Row CategoryTitle={"Romance"} filmsCategory={romance}/>
          <Row CategoryTitle={"Comedy"} filmsCategory={comedy}/>
          <Row CategoryTitle={"Horror"} filmsCategory={horror}/>
          <Row CategoryTitle={"Crime"} filmsCategory={crime}/>
          <Row CategoryTitle={"Drama"} filmsCategory={drama}/>
          <Row CategoryTitle={"Fantasy"} filmsCategory={fantasy}/>
          <Row CategoryTitle={"Family"} filmsCategory={family}/>
        </section>
      </main>
    </div>
  );
}

export const getStaticProps = wrapper.getStaticProps(wrapper => async () => {
  
  const [fetchActionMovies, fetchAdventureMovies, fetchAnimationMovies,fetchCrimeMovies,fetchComedyMovies,fetchDocumentariesMovies, fetchDramaMovies,fetchFamilyMovies,  fetchFantasyMovies, fetchHistoryMovies, fetchHorrorMovies, fetchNetflixOriginalsMovies, fetchRomanceMovies, fetchScienceFictionMovies, fetchTopRatedMovies, fetchTrendingMovies] = await Promise.all([
    fetch(request.fetchAction), fetch(request.fetchAdventure), fetch(request.fetchAnimation), fetch(request.fetchCrime), fetch(request.fetchComedy), fetch(request.fetchDocumentaries), fetch(request.fetchDrama), fetch(request.fetchFamily), fetch(request.fetchFantasy), fetch(request.fetchHistory), fetch(request.fetchHorror), fetch(request.fetchNetflixOriginals), fetch(request.fetchRomance), fetch(request.fetchScienceFiction), fetch(request.fetchTopRated), fetch(request.fetchTrending)
  ]);
  
  const [ActionMovies, AdventureMovies, AnimationMovies,CrimeMovies,ComedyMovies,Documentaries, DramaMovies,FamilyMovies,  FantasyMovies, HistoryMovies, HorrorMovies, NetflixOriginalsMovies, RomanceMoviesMovies, ScienceFictionMovies, TopRatedMovies, TrendingMovies] = await Promise.all([fetchActionMovies.json(), fetchAdventureMovies.json(), fetchAnimationMovies.json(),fetchCrimeMovies.json(),fetchComedyMovies.json(),fetchDocumentariesMovies.json(), fetchDramaMovies.json(),fetchFamilyMovies.json(),  fetchFantasyMovies.json(), fetchHistoryMovies.json(), fetchHorrorMovies.json(), fetchNetflixOriginalsMovies.json(), fetchRomanceMovies.json(), fetchScienceFictionMovies.json(), fetchTopRatedMovies.json(), fetchTrendingMovies.json()])
    
  wrapper.dispatch(getActionFilm(ActionMovies.results))
  wrapper.dispatch(getAdventureFilm(AdventureMovies.results))
  wrapper.dispatch(getAnimationFilm(AnimationMovies.results))
  wrapper.dispatch(getCrimeFilm(CrimeMovies.results))
  wrapper.dispatch(getComedyFilm(ComedyMovies.results))
  wrapper.dispatch(getDocumentariesFilm(Documentaries.results))
  wrapper.dispatch(getDramaFilm(DramaMovies.results))
  wrapper.dispatch(getFamilyFilm(FamilyMovies.results))
  wrapper.dispatch(getFantasyFilm(FantasyMovies.results))
  wrapper.dispatch(getHistoryFilm(HistoryMovies.results))
  wrapper.dispatch(getHorrorFilm(HorrorMovies.results))
  wrapper.dispatch(getNetflixOriginalsFilm(NetflixOriginalsMovies.results))
  wrapper.dispatch(getRomanceFilm(RomanceMoviesMovies.results))
  wrapper.dispatch(getScienceFictionFilm(ScienceFictionMovies.results))
  wrapper.dispatch(getTopRatedFilm(TopRatedMovies.results))
  wrapper.dispatch(getTrendingFilm(TrendingMovies.results))
})
