/* eslint-disable react/react-in-jsx-scope */
import Head from 'next/head';
import Header from '../components/Header';
import Footer from '../components/Footer';
import Banner from '../components/Banner';
import Row from '../components/Row';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflux</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Row> row</Row>
      <Footer />
    </div>
  );
}
